spring:
  application:
    name: channel-server

  # Redis Configuration (Upstash)
  data:
  redis:
    host: ${SPRING_REDIS_HOST:funny-monkey-29399.upstash.io}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD}
    ssl: ${SPRING_REDIS_SSL:true}
    timeout: 5000




# ───────────────
# Server Settings
# ───────────────
server:
  port: ${SERVER_PORT:8083}

# ───────────────
# Eureka Client
# ───────────────
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:https://eureka-service-<your-app>.onrender.com/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}


# ───────────────
# JWT Secret (read from env)
# ───────────────
jwt:
  secret: ${JWT_SECRET_KEY:supreme-solutions-secret-key-9876543210@#jwt}

# ───────────────
# Logging & Profiles
# ───────────────
logging:
  level:
    root: INFO
