spring:
  application:
    name: channel-server

  # Redis Configuration (Upstash)
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}
      ssl:
        enabled: ${SPRING_REDIS_SSL:true}

# ───────────────
# Server Settings
# ───────────────
server:
  port: ${SERVER_PORT:8083}

# ───────────────
# Eureka Client
# ───────────────
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:https://eureka-server-sk4j.onrender.com/eureka/}
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${random.value}
    metadata-map:
      management.port: ${server.port}

# ───────────────
# JWT Secret (read from env)
# ───────────────
jwt:
  secret: ${JWT_SECRET_KEY:supreme-solutions-secret-key-9876543210@#jwt}

# ───────────────
# Logging & Profiles
# ───────────────
logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
